-- Otorgar todos los privilegios al usuario VSC-COPILOT para la base de datos inventario
GRANT ALL PRIVILEGES ON *.* TO `VSC-COPILOT`@`%` IDENTIFIED BY PASSWORD '*BA0044C2A9E33A9C54B06147F2EDE779EA631464' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `inventario`.* TO `VSC-COPILOT`@`%`;
GRANT ALL PRIVILEGES ON `inventario`.* TO `VSC-COPILOT`@`%` WITH GRANT OPTION;
